/* 
 * This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details.
 */ 

#ifndef __TLMODDER_CHARCREATE_H__
#define __TLMODDER_CHARCREATE_H__

char const *charactercreate_layout_0 = ""
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<GUILayout >\n"
"<Window Type=\"DefaultWindow\" Name=\"Root\" >\n"
"<Property Name=\"UnifiedMaxSize\" Value=\"{{1,0},{1,0}}\" />\n"
"<Property Name=\"UnifiedAreaRect\" Value=\"{{0,0},{0,0},{1,0},{1,0}}\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"<Window Type=\"GuiLook/StaticImage\" Name=\"TopBarB\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{.5,0},{0,0}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,1024},{0,140}}\" />\n"
"<Window Type=\"GuiLook/StaticImage\" Name=\"TopBar\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{-.5,0},{0,0}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,1024},{0,140}}\" />\n"
"<Property Name=\"Image\" Value=\"set:Logo image:topbar\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"<Property Name=\"ClippedByParent\" Value=\"False\" />\n"
"</Window>\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticImage\" Name=\"TopBarLeft\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{0,0}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,225},{0,88}}\" />\n"
"<Property Name=\"Image\" Value=\"set:Logo image:topbarleft\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticImage\" Name=\"TopBarRight\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{1,-225},{0,0}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,225},{0,88}}\" />\n"
"<Property Name=\"Image\" Value=\"set:Logo image:topbarright\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticImage\" Name=\"BottomBarB\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{.5,0},{1,-89}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,1024},{0,89}}\" />\n"
"<Window Type=\"GuiLook/StaticImage\" Name=\"BottomBar\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{-.5,0},{1,-89}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,1024},{0,89}}\" />\n"
"<Property Name=\"Image\" Value=\"set:Logo image:bottombar\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"<Property Name=\"ClippedByParent\" Value=\"False\" />\n"
"</Window>\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticImage\" Name=\"BottomBarLeft\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{1,-89}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,225},{0,89}}\" />\n"
"<Property Name=\"Image\" Value=\"set:Logo image:bottombarleft\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticImage\" Name=\"BottomBarRight\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{1,-225},{1,-89}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,225},{0,89}}\" />\n"
"<Property Name=\"Image\" Value=\"set:Logo image:bottombarright\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticTextOutline\" Name=\"CharacterClassHeader\" >\n"
"<Property Name=\"Text\" Value=\"1\"/>\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{.5,-300},{0,110}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,600},{0,32}}\" />\n"
"<Property Name=\"Font\" Value=\"SerifBig\" />\n" 
"<Property Name=\"Text\" Value=\"Select Hero Class\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"<Property Name=\"AlwaysOnTop\" Value=\"True\" />\n"
"<Property Name=\"HorzTextFormatting\" Value=\"CentreAligned\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticTextOutline\" Name=\"CharacterClass\" >\n"
"<Property Name=\"Text\" Value=\"1\"/>\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{.5,-300},{1,-180}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,600},{0,60}}\" />\n"
"<Property Name=\"Text\" Value=\"Destroyer\" />\n"
"<Property Name=\"Font\" Value=\"SerifHuge\" />\n" 
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"<Property Name=\"AlwaysOnTop\" Value=\"True\" />\n"
"<Property Name=\"HorzTextFormatting\" Value=\"CentreAligned\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticText\" Name=\"CharacterClassDescription\" >\n"
"<Property Name=\"Text\" Value=\"1\"/>\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{.5,-150},{1,-145}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,300},{0,64}}\" />\n"
"<Property Name=\"Font\" Value=\"SerifSmall\" />\n" 
"<Property Name=\"Text\" Value=\"The Destroyer excels at melee combat and channels the power of his ancestors\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"<Property Name=\"AlwaysOnTop\" Value=\"True\" />\n"
"<Property Name=\"HorzTextFormatting\" Value=\"WordWrapCentreAligned\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/StandardButton\" Name=\"Back\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{.5,-400},{1,-64}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,246},{0,44}}\" />\n"
"<Property Name=\"Text\" Value=\"Back\"/>\n"
"<Property Name=\"onClick\" Value=\"guiBack\"/>\n"
"</Window>\n"
"<Window Type=\"GuiLook/StandardButton\" Name=\"CreatePlayer\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{.5,154},{1,-64}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,246},{0,44}}\" />\n"
"<Property Name=\"Text\" Value=\"OK\"/>\n"
"<Property Name=\"onClick\" Value=\"guiNewGame\"/>\n"
"</Window>\n"
"<Window Type=\"GuiLook/ItemText\" Name=\"PortraitBox\" >\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,30},{.4,-200}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,150},{0,550}}\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"<Window Type=\"GuiLook/StaticText\" Name=\"Orig\" >\n"
"<Property Name=\"Text\" Value=\"Original\" />\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{0,2}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,150},{0,24}}\" />\n"
"<Property Name=\"HorzTextFormatting\" Value=\"CentreAligned\" />\n"
"<Property Name=\"Font\" Value=\"SerifBig\" />\n" 
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticText\" Name=\"Class1\" >\n"
"<Property Name=\"Text\" Value=\"Classes\" />\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{0,24}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,150},{0,24}}\" />\n"
"<Property Name=\"HorzTextFormatting\" Value=\"CentreAligned\" />\n"
"<Property Name=\"Font\" Value=\"SerifBig\" />\n" 
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/RadioButton\" Name=\"Destroyer\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,7},{0,47}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,64},{0,64}}\" />\n"
"<Property Name=\"SelectedImage\" Value=\"set:Logo image:destroyericonselected\" />\n"
"<Property Name=\"HoverImage\" Value=\"set:Logo image:destroyericonlit\" />\n"
"<Property Name=\"UnselectedImage\" Value=\"set:Logo image:destroyericon\" />\n"
"<Property Name=\"Tooltip\" Value=\"Select Destroyer\" />\n"
"<Property Name=\"onClick\" Value=\"guiSelect1\"/>\n"
"</Window>\n"
"<Window Type=\"GuiLook/RadioButton\" Name=\"Vanquisher\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,79},{0,47}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,64},{0,64}}\" />\n"
"<Property Name=\"SelectedImage\" Value=\"set:Logo image:vanquishericonselected\" />\n"
"<Property Name=\"HoverImage\" Value=\"set:Logo image:vanquishericonlit\" />\n"
"<Property Name=\"UnselectedImage\" Value=\"set:Logo image:vanquishericon\" />\n"
"<Property Name=\"ID\" Value=\"1\" />\n"
"<Property Name=\"Tooltip\" Value=\"Select Vanquisher\" />\n"
"<Property Name=\"onClick\" Value=\"guiSelect1\"/>\n"
"</Window>\n"
"<Window Type=\"GuiLook/RadioButton\" Name=\"Alchemist\">\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,43},{0,116}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,64},{0,64}}\" />\n"
"<Property Name=\"SelectedImage\" Value=\"set:Logo image:alchemisticonselected\" />\n"
"<Property Name=\"HoverImage\" Value=\"set:Logo image:alchemisticonlit\" />\n"
"<Property Name=\"UnselectedImage\" Value=\"set:Logo image:alchemisticon\" />\n"
"<Property Name=\"ID\" Value=\"2\" />\n"
"<Property Name=\"Tooltip\" Value=\"Select Alchemist\" />\n"
"<Property Name=\"onClick\" Value=\"guiSelect1\"/>\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticText\" Name=\"Cust\" >\n"
"<Property Name=\"Text\" Value=\"Custom\" />\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{0,187}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,140},{0,24}}\" />\n"
"<Property Name=\"HorzTextFormatting\" Value=\"CentreAligned\" />\n"
"<Property Name=\"Font\" Value=\"SerifBig\" />\n" 
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/StaticText\" Name=\"Class2\" >\n"
"<Property Name=\"Text\" Value=\"Classes\" />\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{0,209}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,140},{0,24}}\" />\n"
"<Property Name=\"HorzTextFormatting\" Value=\"CentreAligned\" />\n"
"<Property Name=\"Font\" Value=\"SerifBig\" />\n" 
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"</Window>\n"
"<Window Type=\"GuiLook/ScrollablePane\" Name=\"PortraitBoxScroll\" >\n"
"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{0,232}}\" />\n"
"<Property Name=\"UnifiedSize\" Value=\"{{0,150},{0,305}}\" />\n"
"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
"<Property Name=\"HorizontalScrollbar\" Value=\"Disabled\" />\n"
"<!-- non-original classes here -->\n";

char const *charactercreate_layout_1 = ""
"</Window>\n"
"</Window>\n"
"<Window Type=\"GuiLook/ItemText\" Name=\"PetBox\" >\n"
	"<Property Name=\"UnifiedPosition\" Value=\"{{1,-180},{.5,-190}}\" />\n"
	"<Property Name=\"UnifiedSize\" Value=\"{{0,150},{0,380}}\" />\n"
	"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
	"<Window Type=\"GuiLook/StaticText\" Name=\"PetTitle\" >\n"
		"<Property Name=\"Text\" Value=\"Pet\" />\n"
		"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{0,5}}\" />\n"
		"<Property Name=\"UnifiedSize\" Value=\"{{0,150},{0,24}}\" />\n"
		"<Property Name=\"HorzTextFormatting\" Value=\"CentreAligned\" />\n"
		"<Property Name=\"Font\" Value=\"SerifBig\" />\n" 
		"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
	"</Window>\n"
	
	"<Window Type=\"GuiLook/StaticText\" Name=\"PetName\" >\n"
		"<Property Name=\"Text\" Value=\"Pet Name\" />\n"
		"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{1,-64}}\" />\n"
		"<Property Name=\"UnifiedSize\" Value=\"{{0,150},{0,24}}\" />\n"
		"<Property Name=\"HorzTextFormatting\" Value=\"CentreAligned\" />\n"
		"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
	"</Window>\n"
	
	"<Window Type=\"GuiLook/ItemText\" Name=\"TextBoxPet\" >\n"
		"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{1,-34}}\" />\n"
		"<Property Name=\"UnifiedSize\" Value=\"{{0,150},{0,32}}\" />\n"
		"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
	"</Window>\n"
	"<Window Type=\"GuiLook/Editbox\" Name=\"EditBoxPet\" >\n"
		"<Property Name=\"Text\" Value=\"\" />\n"
		"<Property Name=\"MaxTextLength\" Value=\"12\" />\n"
		"<Property Name=\"UnifiedPosition\" Value=\"{{0,0},{1,-34}}\" />\n"
		"<Property Name=\"UnifiedSize\" Value=\"{{0,140},{0,32}}\" />\n"
	"</Window>\n"
	
	"<Window Type=\"GuiLook/ScrollablePane\" Name=\"PetScrollBox\" >\n"
		"<Property Name=\"UnifiedPosition\" Value=\"{{0,-5},{0,40}}\" />\n"
		"<Property Name=\"UnifiedSize\" Value=\"{{0,155},{0,260}}\" />\n"
		"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
		"<Property Name=\"HorizontalScrollbar\" Value=\"Disabled\" />\n";


char const *charactercreate_layout_2 = ""
	"</Window>"
"</Window>\n"
	"<Window Type=\"GuiLook/ItemText\" Name=\"TextBox\" >\n"
		"<Property Name=\"UnifiedPosition\" Value=\"{{.5,-70},{1,-60}}\" />\n"
		"<Property Name=\"UnifiedSize\" Value=\"{{0,140},{0,32}}\" />\n"
		"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
	"</Window>\n"
	"<Window Type=\"GuiLook/Editbox\" Name=\"EditBox\" >\n"
		"<Property Name=\"Text\" Value=\"\" />\n"
		"<Property Name=\"MaxTextLength\" Value=\"12\" />\n"
		"<Property Name=\"UnifiedPosition\" Value=\"{{.5,-70},{1,-60}}\" />\n"
		"<Property Name=\"UnifiedSize\" Value=\"{{0,140},{0,32}}\" />\n"
	"</Window>\n"
	"<Window Type=\"GuiLook/StaticText\" Name=\"Name\" >\n"
		"<Property Name=\"Text\" Value=\"Character Name\" />\n"
		"<Property Name=\"UnifiedPosition\" Value=\"{{.5,-70},{1,-88}}\" />\n"
		"<Property Name=\"UnifiedSize\" Value=\"{{0,140},{0,24}}\" />\n"
		"<Property Name=\"HorzTextFormatting\" Value=\"CentreAligned\" />\n"
		"<Property Name=\"MousePassThroughEnabled\" Value=\"True\" />\n"
	"</Window>\n"
"</Window>\n"
"</GUILayout>\n";

#endif
